baseURL = 'https://lucashadfield.github.io/'
languageCode = 'en-us'
title = 'Lucas Hadfield'
theme = 'ananke'

[params]
mainSections = ['posts']
post_content_classes = 'sans-serif'
custom_css = ['custom.css']
