baseURL = "https://blog.hadfield.dev/"
languageCode = "en-us"
title = "blog.hadfield.dev"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
  featured_image = "/images/featured.png"
  site_logo = ""
  description = ""
  body_classes = "sans-serif bg-near-white"
  post_content_classes = "sans-serif"
  cover_dimming_class = "bg-black-0"
  omit_header_text = true
  custom_css = ["custom.css"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = true

[params.social]
  github = "lucashadfield"
  linkedin = "lucashadfield"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20

